version: '3'

services:

services:
  db:
    image: "mdillon/postgis"
    environment:
        POSTGRES_PASSWORD: "admin"
        POSTGRES_USER: "admin"

  mapperapi:
    image: mapperapi
    ports: 
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile