version: '3'

services:

services:
  mapperapi:
    image: mapperapi
    build:
      context: .
      dockerfile: Dockerfile
      depends_on:
          - db
    db:
        image: "mdillon/postgis"
        environment:
            POSTGRES_PASSWORD: "admin"
            POSTGRES_USER: "admin"